# ── Terminal ───────────────────────────────────────────────────────────────────
set -s default-terminal "${TERM}"
# True color support
set-option -ga terminal-overrides ",*256color*:Tc"
# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# ── Shell ──────────────────────────────────────────────────────────────────────
if-shell 'uname | grep -q Linux'  'set-option -g default-shell /usr/bin/fish; set-option -g default-command "/usr/bin/fish -i"'
if-shell 'uname | grep -q Darwin' 'set-option -g default-shell /opt/homebrew/bin/fish; set-option -g default-command "/opt/homebrew/bin/fish -i"'

# ── General options ────────────────────────────────────────────────────────────
setw -g mouse on
set-option -g focus-events on

# Windows & panes start at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Stay in tmux when last window of a session closes
set-option -g detach-on-destroy off

# Status bar
set-option -g status-position top
set -g status-left-length 100
set -g status-right-length 100
set -g status 2
set -g 'status-format[1]' ''

# Copy mode
setw -g mode-keys vi

# Pane borders
set -g pane-border-lines double

# Window titles
set -g set-titles on
set -g set-titles-string "#T"
