# ── tmux.conf — entry point ────────────────────────────────────────────────────
source ~/.config/tmux/options.conf
source ~/.config/tmux/keybinds.conf
source ~/.config/tmux/theme.conf
source ~/.config/tmux/plugins.conf

# ── Plugins ────────────────────────────────────────────────────────────────────
# Install TPM:
#   git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (must be last)
run '~/.tmux/plugins/tpm/tpm'
